version: '3.8'

services:
  setup:
    image: vetfun-app:latest
    networks:
      - minha_rede
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: none
    environment:
      - APP_ENV=production
      - DB_HOST=db
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_backup:/backup
    command: ["/usr/local/bin/production-setup.sh"]
    depends_on:
      - app
      - db

volumes:
  db_backup:
    external: true

networks:
  minha_rede:
    external: true
